create table "policy"(
	Data_id int,
	"C1M_School closing" int,
    c1m_flag int,
    "C2M_Workplace closing" int,
    c2m_flag int,
    "C3M_Cancel public events" int,
    c3m_flag int,
    "C4M_Restrictions on gatherings" int,
    c4m_flag int,
    "C5M_Close public transport" int,
    c5m_flag int,
    "C6M_Stay at home requirements" int,
    c6m_flag int,
    "C7M_Restrictions on internal movement" int,
    c7m_flag int,
    "C8EV_International travel controls" int,
	"E1_Income support" int,
    e1_flag int,
    "E2_Debt/contract relief" int,
    "E3_Fiscal measures" real,
    "E4_International support" double precision,
	"H1_Public information campaigns" int,
    h1_flag int,
    "H2_Testing policy" int,
    "H3_Contact tracing" int,
    "H4_Emergency investment in healthcare" real,
    "H5_Investment in vaccines" real,
    "H6M_Facial Coverings" int,
    h6m_flag int,
    "H7_Vaccination policy" int,
    h7_flag int,
    "H8M_Protection of elderly people" int,
    h8m_flag int,
	"V1_Vaccine Prioritisation (summary)" int,
    "V2A_Vaccine Availability (summary)" int,
    "V2B_Vaccine age eligibility/availability age floor (general)" varchar(20),
    "V2C_Vaccine age eligibility/availability age floor (at risk)" varchar(20),
    "V2D_Medically/ clinically vulnerable (Non-elderly)" int,
    v2e_education int,
    "V2F_Frontline workers  (non healthcare)" int,
    "V2G_Frontline workers  (healthcare)" int,
    "V3_Vaccine Financial Support (summary)" int,
    "V4_Mandatory Vaccination (summary)" int,
	primary key(Data_id)
)